<?php
/**
 * @author Jan Habbo Brüning <jan.habbo.bruening@gmail.com>
 *
 * @noinspection PhpUnnecessaryLocalVariableInspection
 * @noinspection SqlNoDataSourceInspection
 * @noinspection PhpFullyQualifiedNameUsageInspection
 */

namespace Frootbox\Db\Dbms;

class Mysql implements Interfaces\Dbms
{
    protected $pdo;

    protected $schema;

    /**
     * Create a MySQL PDO adapter.
     *
     * @param string $host MySQL host.
     * @param string $schema Database schema name.
     * @param string $user Database user.
     * @param string $password Database password.
     * @param string $charset Connection charset.
     */
    public function __construct(string $host, string $schema, string $user, string $password, string $charset = 'utf8mb4')
    {
        $this->connect($host, $schema, $user, $password, $charset);
    }

    /**
     * Open the PDO connection.
     *
     * @param string $host MySQL host.
     * @param string $schema Database schema name.
     * @param string $user Database user.
     * @param string $password Database password.
     * @param string $charset Connection charset.
     * @return $this
     */
    public function connect(string $host, string $schema, string $user, string $password, string $charset): Mysql
    {
        $this->schema = $schema;

        $dsn = 'mysql:dbname=' . $schema . ';host=' . $host . ';charset=' . $charset;

        $this->pdo = new \PDO($dsn, $user, $password, [
            \PDO::MYSQL_ATTR_FOUND_ROWS => true,
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
        ]);

        return $this;
    }

    /**
     * Execute a delete query from adapter parameters.
     *
     * @deprecated Prefer higher-level repository APIs.
     *
     * @param array $params Delete query parameters.
     * @return true
     */
    public function delete(array $params)
    {
        $query = new \Frootbox\Db\Dbms\Mysql\Queries\Delete($params);

        $this->execute($query);

        return true;
    }

    /**
     * Prepare, bind, and execute a MySQL query object.
     *
     * @param \Frootbox\Db\Dbms\Mysql\Queries\Interfaces\QueryInterface $query Query object.
     * @return mixed Executed PDO statement.
     */
    public function execute(Mysql\Queries\Interfaces\QueryInterface $query)
    {
        $sql = $query->toString();

        $stmt = $this->pdo->prepare($sql);

        foreach ($query->getParameters() as $parameter) {

            if ($parameter->getSkip()) {
                continue;
            }

            $stmt->bindValue($parameter->getKey(), $parameter->getValue());
        }

        $stmt->execute();

        return $stmt;
    }

    /**
     * Execute a select query from adapter parameters.
     *
     * @deprecated Prefer higher-level repository APIs.
     *
     * @param array $params Select query parameters.
     * @return array<int, array<string, mixed>>
     */
    public function fetch(array $params): array
    {
        $query = new \Frootbox\Db\Dbms\Mysql\Queries\Select($params);

        $result = $this->execute($query);

        return $result->fetchAll();
    }

    /**
     * Return the last auto-increment id generated by PDO.
     *
     * @return mixed
     */
    public function getLastInsertId()
    {
        return $this->pdo->lastInsertId();
    }

    /**
     * Return the connected database schema name.
     *
     * @return string
     */
    public function getSchema(): string
    {
        return $this->schema;
    }

    /**
     * Prepare a raw SQL statement.
     *
     * @param string $sql SQL statement.
     * @return mixed PDOStatement.
     */
    public function prepare(string $sql)
    {
        $stmt = $this->pdo->prepare($sql);

        return $stmt;
    }

    /**
     * Execute a raw SQL query.
     *
     * @param string $sql SQL query.
     * @return mixed PDOStatement.
     */
    public function query($sql)
    {
        $stmt = $this->pdo->query($sql);

        return $stmt;
    }

    /**
     * Roll back the active PDO transaction.
     *
     * @return void
     */
    public function rollback(): void
    {
        $this->pdo->rollBack();
    }

    /**
     * Start a PDO transaction if none is active.
     *
     * @return void
     */
    public function transactionStart(): void
    {
        if (!$this->pdo->inTransaction()) {
            $this->pdo->beginTransaction();
        }
    }

    /**
     * Commit the active PDO transaction.
     *
     * @return void
     */
    public function transactionCommit()
    {
        $this->pdo->commit();
    }

    /**
     * @deprecated
     *
     * Execute an update query from adapter parameters.
     *
     * @param array $params Update query parameters.
     * @return void
     */
    public function update(array $params): void
    {
        $query = new \Frootbox\Db\Dbms\Mysql\Queries\Update($params);

        $this->execute($query);
    }
}
