<?php
/**
 * @author Jan Habbo Brüning <jan.habbo.bruening@gmail.com>
 *
 * @noinspection PhpUnnecessaryLocalVariableInspection
 * @noinspection SqlNoDataSourceInspection
 * @noinspection PhpFullyQualifiedNameUsageInspection
 */

namespace Frootbox\Db;

class Db
{
    protected $dbms;
    protected $transactionLevel = 0;
    protected $variables = [ ];

    /**
     * Create the database facade around a concrete DBMS adapter.
     *
     * @param Dbms\Interfaces\Dbms $dbms Database adapter implementation.
     */
    public function __construct(\Frootbox\Db\Dbms\Interfaces\Dbms $dbms)
    {
        $this->dbms = $dbms;
    }

    /**
     * Delete rows using the adapter query format.
     *
     * @param array $params Delete parameters, including table, where, and optional limit.
     * @return true
     */
    public function delete(array $params)
    {
        return $this->dbms->delete($params);
    }

    /**
     * Fetch rows and wrap the raw records in a Result object.
     *
     * @param array $params Select parameters, including table, where, order, limit, and select.
     * @return Result
     */
    public function fetch(array $params)
    {
        $rows = $this->dbms->fetch($params);

        $result = new \Frootbox\Db\Result($rows, $this);

        return $result;
    }

    /**
     * Fetch the first column from the first row of a prepared SQL statement.
     *
     * @param string $sql SQL statement.
     * @param array|null $params Placeholder values keyed by placeholder name.
     * @return mixed First column value, or false when the result set is empty.
     */
    public function fetchColumn(string $sql, array $params = null): mixed
    {
        $stmt = $this->prepare($sql);

        if (!empty($params)) {

            foreach ($params as $tag => $value) {
                $stmt->bindValue($tag, $value);
            }
        }

        $stmt->execute();

        return $stmt->fetchColumn();
    }

    /**
     * Return the last auto-increment id generated by the connection.
     *
     * @return mixed
     */
    public function getLastInsertId()
    {
        return $this->dbms->getLastInsertId();
    }

    /**
     * @deprecated
     *
     * Create a model/repository instance.
     *
     * @template TModel of Model
     * @param class-string<TModel> $model Model class name.
     * @return TModel
     */
    public function getModel($model): Model
    {
        return new $model($this);
    }

    /**
     * Create a generic model for a table without a custom repository class.
     *
     * @param string $table Table name.
     * @return Model<Row>
     */
    public function getModelRaw($table): Model
    {
        $model = new Model($this);
        $model->setTable($table);
        $model->setClass(Row::class);

        $model->setTable($table);

        return $model;
    }

    /**
     * Create a repository instance for the given model class.
     *
     * @template TModel of Model
     * @param class-string<TModel> $model Model class name.
     * @return TModel
     */
    public function getRepository($model): Model
    {
        return new $model($this);
    }

    /**
     * Get the currently selected database schema name.
     *
     * @return string
     */
    public function getSchema(): string
    {
        return $this->dbms->getSchema();
    }

    /**
     * Resolve a previously registered SQL placeholder variable.
     *
     * @param string $variable Variable key including braces, for example "{userId}".
     * @return mixed|null
     */
    public function getVariable($variable)
    {
        return $this->variables[$variable] ?? null;
    }

    /**
     * Prepare a raw SQL statement through the adapter.
     *
     * @param string $sql SQL statement.
     * @return mixed Adapter-specific prepared statement.
     */
    public function prepare(string $sql)
    {
        return $this->dbms->prepare($sql);
    }

    /**
     * Execute a raw SQL query through the adapter.
     *
     * @param string $sql SQL query.
     * @return mixed Adapter-specific statement result.
     */
    public function query($sql)
    {
        return $this->dbms->query($sql);
    }

    /**
     * Roll back the active transaction on the adapter.
     *
     * @return void
     */
    public function rollback(): void
    {
        $this->dbms->rollback();
    }

    /**
     * Register a value that can be referenced as "{variable}" in row data.
     *
     * @param string $variable Variable name without braces.
     * @param mixed $value Replacement value.
     * @return $this
     */
    public function setVar($variable, $value): Db
    {
        $this->variables['{' . $variable . '}'] = $value;

        return $this;
    }

    /**
     * Begin a transaction, supporting nested transaction counters.
     *
     * @return $this
     */
    public function transactionStart(): \Frootbox\Db\Db
    {
        if ($this->transactionLevel == 0) {
            $this->dbms->transactionStart();
        }

        ++$this->transactionLevel;

        return $this;
    }

    /**
     * Commit the outermost active transaction.
     *
     * @return $this
     */
    public function transactionCommit(): \Frootbox\Db\Db
    {
        --$this->transactionLevel;

        if ($this->transactionLevel == 0) {
            $this->dbms->transactionCommit();
        }

        return $this;
    }

    /**
     * Update rows using the adapter query format.
     *
     * @param array $params Update parameters, including table, data, where, and optional limit.
     * @return null
     */
    public function update(array $params)
    {
        return $this->dbms->update($params);
    }

    /**
     * Reserved initialization hook for project-specific wrappers.
     *
     * @param mixed $wrapper Project wrapper or container.
     * @param array|null $options Optional initialization options.
     * @return void
     */
    public static function init($wrapper, array $options = null)
    {
        
    }
}
